version: "3.3"
services:
    ui:
        build: ./www
        ports:
            - 8080:80
    gic:
        image: gic 
        ports:
            - 8081:8080
        environment:
            - GITLAB_TOKEN

